# Generated by Django 2.0.5 on 2018-05-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spellcheck', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
