# Generated by Django 2.0.5 on 2018-05-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spellcheck', '0008_auto_20180528_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Spellcheck.User'),
        ),
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.IntegerField(),
        ),
    ]
