# Generated by Django 2.0.5 on 2018-05-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spellcheck', '0013_auto_20180528_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
