# Generated by Django 2.0.5 on 2018-05-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spellcheck', '0016_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='author',
            new_name='user',
        ),
    ]
