# Generated by Django 2.0.5 on 2018-05-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spellcheck', '0019_auto_20180528_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
