# Generated by Django 2.0.5 on 2018-06-03 02:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spellcheck', '0021_auto_20180528_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='text',
        ),
        migrations.AddField(
            model_name='text',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 5, 38, 54, 329656)),
        ),
        migrations.AddField(
            model_name='text',
            name='textChecked',
            field=models.CharField(default='default', max_length=500),
        ),
        migrations.AddField(
            model_name='text',
            name='textInputed',
            field=models.CharField(default='default', max_length=500),
        ),
        migrations.AlterField(
            model_name='text',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
