# Generated by Django 2.0.5 on 2018-06-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spellcheck', '0022_auto_20180603_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='dateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='text',
            name='textChecked',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='text',
            name='textInputed',
            field=models.CharField(max_length=500),
        ),
    ]
