# Generated by Django 2.0.5 on 2018-06-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spellcheck', '0023_auto_20180603_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='session_key',
            field=models.CharField(default='default', max_length=128),
        ),
    ]
