# Generated by Django 2.0.5 on 2018-06-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spellcheck', '0024_text_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='session_key',
            field=models.CharField(max_length=128),
        ),
    ]
