# Generated by Django 2.0.5 on 2018-06-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spellcheck', '0025_auto_20180603_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='text',
            name='dateTimeCreated',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='text',
            name='dateTimeDelete',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='text',
            name='textSuggestion',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
