# Generated by Django 2.0.5 on 2018-06-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spellcheck', '0026_auto_20180607_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='dateTimeCreated',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='text',
            name='dateTimeDelete',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='text',
            name='textSuggestion',
            field=models.CharField(max_length=500),
        ),
    ]
